pipeline {
    agent any

    tools { 
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    stages {
        stage('GIT') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Hadirgh/timesheetproject.git'
            }
        }

        stage('Compile Stage') {
            steps {
                dir('timesheet') {  // <- Exécute Maven dans le sous-dossier 'timesheet'
                    sh 'mvn clean compile'
                }
            }
        }
    }
}
